trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python -m playwright install --with-deps
  displayName: 'Install dependencies'

- script: |
    pytest tests/ --maxfail=1 --disable-warnings -v
  displayName: 'Run Playwright Tests'
