name: Playwright UI Tests

on:
  push:
    branches: [ "githubaction" ]
  pull_request:
    branches: [ "githubaction" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run single test
        run: |
          pytest tests/test_drp.py::test_change_password_page --headed --maxfail=1 --disable-warnings -q

