name: Playwright UI Tests

on:
  push:
    branches: [ "githubaction" ]
  pull_request:
    branches: [ "githubaction" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run single test and generate Allure results
        run: |
          pytest tests/test_drp.py::test_profile_dropdown_visible_options --alluredir=allure-results --headed --maxfail=1 --disable-warnings -q

      - name: Generate Allure HTML Report
        run: |
          allure generate allure-results --clean -o allure-report
        continue-on-error: true  # Optional: avoids breaking the job if no results are found

      - name: Upload Allure Raw Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-raw-results
          path: allure-results

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report
