name: Run Playwright Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install --with-deps
    

    - name: Run all test files and generate HTML report
      run:
        pytest Day3_28_5_25/ --maxfail=1 --disable-warnings -v --html=report.html --self-contained-html

#    - name: Run all test files
#      run: |
#        pytest Day3_28_5_25/ --maxfail=1 --disable-warnings -v

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html




